apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backdeploy
  name: backdeploy
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backdeploy
    spec:
      containers:
      - image: 535002878565.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:latest
        name: projectback
        resources: {}
status: {}
